config/routes.rb
Rails.application.routes.draw do
  get 'order_details/show'
  # Routes for Category
  resources :categories, only: %i[index show]

  # Routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Routes for Course (main content)
  root to: "courses#index"
  get "courses/about"
  resources :courses, only: %i[index show]

  # Routes for User
  get "user/show"
  devise_for :users
  post "/user/:id/update", to: "user#update"
  get "/user/:id", to: "user#show"
  resources :customer_infos, only: %i[show]

  #Routes for order details
  get "order_details/:id", to: "order_details#show"


  # Routes for Cart management
  post "/cart/:id/update", to: "cart#create"
  post "/cart/:id/delete", to: "cart#delete"
  post "/cart/:id/addRegion", to: "cart#addRegion"
  get "/cart", to: "cart#show"

  # Routes for Stripe
  scope "cart/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
  helper_method :current_user
  def create
    logger.debug("adding #{params[:id]} to cart")
    course_id = params[:id].to_i
    # Initialises the session
    session[:cart] ||= []
    # Determines if the item is already inside the cart doesn't push it other it does.
    session[:cart] << course_id unless session[:cart].include?(course_id)
    redirect_to root_path
  end

  def delete
    course_id = params[:id].to_i
    session[:cart].delete(course_id)
    redirect_to root_path
  end

  def show
    require 'json'
    require 'stripe'

    @currentUser = current_user



    #Customer info
    @customerInfo = CustomerInfo.find_by(user_id: @currentUser.id)

    @items_in_cart = session[:cart]
    @test ||= [];
    @subtotal_price = 0;
    @items_in_cart.each do |n|
      @test << Course.find(n)
      @subtotal_price += Course.find(n).price
    end
    if !CustomerInfo.find_by(user_id: @currentUser.id).nil?
      @gst_in_dollars = (@subtotal_price * Province.find_by(id:@customerInfo.province_id).GST)
      @pst_in_dollars = (@subtotal_price * Province.find_by(id:@customerInfo.province_id).PST)
      @hst_in_dollars = (@subtotal_price * Province.find_by(id:@customerInfo.province_id).HST)
      @total_price = @subtotal_price + @hst_in_dollars

    end


  end

  def addRegion
    info = CustomerInfo.create(
        address:       params[:address],
        user_id:       params[:id],
        province_id:   params[:province_id]
      )
      #Updates information on stripe
  Stripe::Customer.update(
    User.find(current_user.id).stripe_customer_id.to_s,
    {
      phone: "1#{params[:phone].to_s}",
      name: params[:fullName].to_s,
      address: {
        country: 'CA',
        line1: params[:address].to_s,
        state: Province.find(params[:province_id]).Province_Name.to_s,
      },
      shipping: {
        address: {
          country: 'CA',
          line1:  params[:address].to_s,
          state: Province.find(params[:province_id]).Province_Name.to_s,
        },
        name: params[:fullName].to_s,
        phone: "1#{params[:phone].to_s}",
      },
    },
  )
      flash[:success]= "Successfully updated user information!"
      if(!session[:cart].nil?)
        redirect_to cart_path
      else
        redirect_to root_path
      end

  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/show.html.erb
<!---Flash Hash Message--->
<% flash.each do |type, msg| %>
  <div class="alert alert-<%=type%>">
    <%= msg %>
  </div>
<% end %>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-6 card border-info">
        <h5 class="card-header">Order Summary</h5>
        <% if !CustomerInfo.find_by(user_id: @currentUser.id).nil? && CustomerInfo.find_by(user_id: @currentUser.id).address.present? %>
          <!--- Order Info --->
          <div class="card-body">
            <% @test.each do |course| %>
              <h1 class="card-title"><%=course.course_title%></h1>
              <p class="card-text"><%= Category.find(course.category_id).category_name%></p>
              <p class="card-text"><%=Difficulty.find(course.difficulty_id).difficulty %></p>
              <p class="card-text"><%= number_to_currency(course.price) %></p>
            <% end %>
          </div>
          <div class="card-body text-end">
            <!---Subtotal--->
            <p class="card-text">Subtotal: <%= @subtotal_price %><p>
            <!---Taxes--->
            <p class="card-text">
              GST (<%= Province.find_by(id:@customerInfo.province_id).GST * 100 %>%): <%= @gst_in_dollars %></p>
            <p class="card-text">
              PST (<%=Province.find_by(id:@customerInfo.province_id).PST * 100 %>%): <%= @pst_in_dollars %></p>
            <p class="card-text">
              HST (GST + PST): <%= @hst_in_dollars %></p>
            <!---Total--->
            <p class="card-text"><strong>Total Price:</strong> <%= number_to_currency(@total_price) %></p>
          </div><br/>
          <div class="card-footer text-end">
            <%= button_to 'Checkout', checkout_create_path,  method: :post, form: {data: {turbo: "false"}}, remote: true, class: 'btn btn-primary' %><br/>
          </div>
        <% else %>
        <!---Requests user to fill in address and province at minimum before procceding--->
        <div class="card-body">
          <h6 class="card-title">Please Fill in your information before continuing</h6>
          <%= form_with url: "cart/#{@currentUser.id}/addRegion", method: :post do |form| %>
            <%= form.label :address, "Address" %>
            <%= form.text_field :address,  required: true, class: 'form-control' %><br>
            <%= form.label :province_id, "Province/Territory" %>
            <%= select_tag :province_id, options_from_collection_for_select(Province.all, 'id', "Province_Name"), class: 'form-control' %>
            <%= submit_tag("Submit", class: 'btn btn-primary mt-2') %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div><br/>