config/routes.rb
Rails.application.routes.draw do
  get 'order_details/show'
  # Routes for Category
  resources :categories, only: %i[index show]

  # Routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Routes for Course (main content)
  root to: "courses#index"
  get "courses/about"
  resources :courses, only: %i[index show]

  # Routes for User
  get "user/show"
  devise_for :users
  post "/user/:id/update", to: "user#update"
  get "/user/:id", to: "user#show"
  resources :customer_infos, only: %i[show]

  #Routes for order details
  get "order_details/:id", to: "order_details#show"


  # Routes for Cart management
  post "/cart/:id/update", to: "cart#create"
  post "/cart/:id/delete", to: "cart#delete"
  post "/cart/:id/addRegion", to: "cart#addRegion"
  get "/cart", to: "cart#show"

  # Routes for Stripe
  scope "cart/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # root_path
  def index
    @courses = Course.includes(:category).order('RANDOM()').page(params[:page]).per(300).all

    # Filter by category
    if params[:category_id].present?
      @courses = @courses.where(category_id: params[:category_id])
      flash.now[:message] = "Showing results for #{Category.find(params[:category_id]).category_name} category."
    end

    # Search by keyword
    if params[:keyword].present?
      @courses = @courses.where("course_title LIKE ?", "%#{params[:keyword]}%")
      flash.now[:message] = "Showing results for courses containing '#{params[:keyword]}'."
    end
  end

  def show
    @course = Course.includes(:category, :difficulty).find(params[:id])
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/about.html.erb
<div class="card border-info mb-3 mx-auto" style="width 200rem;">
  <h1  class="card-header">About <em>uLearn</em></h1>
  <div class="card-body">
    <p class="card-text"><strong>uLearn</strong> is an e-commerce website about selling self-paced online courses for others to
      purchase and expand their knowledge or gain more skills. The target demographic is adult learners who are either currently
      working and just want to expand their skills without having to enroll in a school or commit to a certain time. Or students
      who are curious about different subjects that they may not be learning in school.
    </p>
    <p class="card-text">
      This web application is created by <strong>Uncle Sam</strong>, a partnership by two students - Sam Ferrer and Xam Abados, graduating BIT Students
      of Red River College Polytechnic. This is also their Full-Stack Web Development class final project. Below is the database ERD of this web application.
    </p>
  </div>
  <%= image_tag("Ecommerce_ERD.png",class: " card-img-top img-fluid", alt:"uLearn's ERD") %><br/>

  <h2  class="card-header">Table Descriptions</em></h2>
  <div class="container">
  <div class="row row-cols-3">
    <div class="col">
      <div class="card border-secondary mb-3">
        <div class="card-header">User Table</div>
        <div class="card-body">
          <p class="card-text">Tracks and stores user password and username that is used for logging in to the site.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card border-secondary mb-3">
        <div class="card-header">Customer Info Table</div>
        <div class="card-body">
          <p class="card-text">Stores the information of a particular customer assigned to one particular user. And uses the provinces table to assign to retrieve respective taxes.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card border-secondary mb-3">
        <div class="card-header">Provinces Table</div>
        <div class="card-body">
          <p class="card-text">Holds all the provinces and territories of Canada with their corresponding GST, HST, PST rates. These taxes are applied to the user whenever they do a transaction.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card border-secondary mb-3">
        <div class="card-header">Orders Table</div>
        <div class="card-body">
          <p class="card-text">Provides basic information of an order that is associated with the particular customer.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card border-secondary mb-3">
        <div class="card-header">Courses In Order Table</div>
        <div class="card-body">
          <p class="card-text">Stores the courses that were used in a particular transaction.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card border-secondary mb-3">
        <div class="card-header">Purchased Course Table</div>
        <div class="card-body">
          <p class="card-text">Saves the purchased courses details so that whenever a detail changes on a course the transaction details won’t change.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card border-secondary mb-3">
        <div class="card-header">Courses Table</div>
        <div class="card-body">
          <p class="card-text">Will contain all the current available courses on the website.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card border-secondary mb-3">
        <div class="card-header">Category Table</div>
        <div class="card-body">
          <p class="card-text">Contains all the categories that a course can be assigned. The categories will be updated as time goes on and be used by multiple diff erent courses.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card border-secondary mb-3">
        <div class="card-header">Difficulty Table</div>
        <div class="card-body">
          <p class="card-text">This table will store our difficulty levels that a course can have. These diffi culties can be reused and new diffi culties can be actively created.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<div class="container-fluid">
<!---Flash Hash Message--->
  <% if flash.now[:message] %>
    <div class="alert alert-info alert-dismissible fade show">
      <%= flash[:message] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <h1 class="display-3"><strong>Courses U can Learn!</strong></h1><br/>
  <div class="container-fluid d-flex flex-row-reverse">
    <%= paginate @courses %>
    <%= session[:cart] %>
  </div>

<div class="table-responsive">
  <table class="table table-sm table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">Course Name</th>
        <th scope="col">Course Category</th>
        <th scope="col">Date Published</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <% @courses.each do |course| %>
        <tr>
          <td><%= link_to course.course_title, course %></td>
          <td><%= link_to course.category.category_name, category_path(course.category) %></td>
          <td><%= course.publish_date.strftime('%Y, %B %d') %></td>
          <td>
            <!---Changes the function of the add to cart--->
              <% if user_signed_in? %>
              <!---Allows user to add items to cart if logged in --->
                <% if !session[:cart].nil? && session[:cart].include?(course.id) %>
                  <%= form_with url:"cart/#{course.id}/delete", method: :post do %>
                    <%= button_tag "Remove From Cart", class: 'btn btn-outline-secondary' %>
                  <% end %>
                <% else %>
                  <%= form_with url:"cart/#{course.id}/update", method: :post do %>
                  <%= button_tag "Add to cart", class: 'btn btn-outline-primary' %>
                  <% end %>
                <% end %>
              <% else %>
              <!---If the user is not signed in the Add to cart redirects to a register/login --->
                <%= form_with url:new_user_session_path, method: :get do %>
                  <%= button_tag "Add to Cart", class: 'btn btn-outline-primary' %>
                <% end %>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <br/>
  <div class="d-flex flex-row-reverse">
    <%= paginate @courses %>
  </div>
</div>

app/views/courses/show.html.erb
<div class="card border-info mb-3 mx-auto" style="max-width: 75rem;">
  <h5 class="card-header"><%= @course.category.category_name %><%= session[:cart] %></h5>
  <div class="card-body">
    <h1 class="card-title"><%= @course.course_title %></h1><br/>
    <p class="card-text"><strong>Release Date:</strong> <%= @course.publish_date.strftime('%B %d, %Y') %></p>
    <p class="card-text"><strong>Number of Lectures:</strong> <%= @course.number_of_lectures %></p>
    <p class="card-text"><strong>Difficulty Level:</strong> <%= @course.difficulty.difficulty %></p>
    <p class="card-text"><strong>Hour Duration:</strong> <%= @course.course_length %></p>

    <%# Price Conditional %>
    <% if @course.price == 0 %>
      <p class="card-text"><strong>Price:</strong> This course is free!</p>
    <% else %>
      <p class="card-text"><strong>Price:</strong> <%= number_to_currency(@course.price) %></p>
      <% if user_signed_in? %>
        <!---Allows user to add items to cart if logged in --->
        <% if !session[:cart].nil? && session[:cart].include?(@course.id) %>
          <%= form_with url:"cart/#{@course.id}/delete", method: :post do %>
            <%= button_tag "Remove From Cart", class: 'btn btn-outline-secondary' %><% end %>
        <% else %>
          <%= form_with url:"../cart/#{@course.id}/update", method: :post do %>
            <%= button_tag "Add to cart", class: 'btn btn-outline-primary' %><% end %>
        <% end %>
      <% else %>
        <!---If the user is not signed in the Add to cart redirects to a register/login --->
        <%= form_with url:new_user_session_path, method: :get do %>
          <%= button_tag "Add to Cart", class: 'btn btn-outline-primary' %><% end %>
      <% end %>
    <% end %>
  </div>
</div><br/>