config/routes.rb
Rails.application.routes.draw do
  get 'order_details/show'
  # Routes for Category
  resources :categories, only: %i[index show]

  # Routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Routes for Course (main content)
  root to: "courses#index"
  get "courses/about"
  resources :courses, only: %i[index show]

  # Routes for User
  get "user/show"
  devise_for :users
  post "/user/:id/update", to: "user#update"
  get "/user/:id", to: "user#show"
  resources :customer_infos, only: %i[show]

  #Routes for order details
  get "order_details/:id", to: "order_details#show"


  # Routes for Cart management
  post "/cart/:id/update", to: "cart#create"
  post "/cart/:id/delete", to: "cart#delete"
  post "/cart/:id/addRegion", to: "cart#addRegion"
  get "/cart", to: "cart#show"

  # Routes for Stripe
  scope "cart/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses, dependent: :destroy
  validates :category_name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :difficulty
  belongs_to :category
  validates :course_title, :price, :difficulty_id, :category_id, :publish_date, presence:true
  validates :price, numericality: true
  validates :difficulty_id, :category_id, numericality: { only_integer: true }
end

app/models/courses_in_order.rb
class CoursesInOrder < ApplicationRecord
  belongs_to :order
  has_many :purchased_course, dependent: :destroy
  validates :order_id, :purchased_course_id, numericality: { only_integer: true }
end

app/models/customer_info.rb
class CustomerInfo < ApplicationRecord
  belongs_to :user
  belongs_to :province
  has_many :orders , dependent: :destroy

  validates :user_id, :province_id, numericality: { only_integer: true }
end

app/models/difficulty.rb
class Difficulty < ApplicationRecord
  has_many :courses, dependent: :destroy
  has_many :purchased_course, dependent: :destroy

  validates :difficulty, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer_info
  has_many :courses_in_order, dependent: :destroy
  validates :customer_info_id,	:stripe_session_id, :order_date,	:price,	:GST,	:HST,	:PST, presence: true
  validates :GST, :HST, :PST, numericality: true
  validates :customer_info_id, numericality: { only_integer: true }
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customer_infos, dependent: :destroy
  validates :Province_Name,:GST, :HST, :PST, presence: true
  validates :GST, :HST, :PST, numericality: true
end

app/models/purchased_course.rb
class PurchasedCourse < ApplicationRecord
  belongs_to :difficulty
  belongs_to :category
  has_one :courses_in_order

  validates :course_title, :price, :number_of_lectures, :difficulty_id,	:course_length,	:category_id,	:publish_date, presence: true
  validates :price, numericality: true
  validates :difficulty_id, :category_id, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :customer_infos, dependent: :destroy
  has_many :purchased_courses, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def to_s
    email
  end

  after_create do
    customer = Stripe::Customer.create(email: email)
    update(stripe_customer_id: customer.id)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
  helper_method :current_user
  def create
    logger.debug("adding #{params[:id]} to cart")
    course_id = params[:id].to_i
    # Initialises the session
    session[:cart] ||= []
    # Determines if the item is already inside the cart doesn't push it other it does.
    session[:cart] << course_id unless session[:cart].include?(course_id)
    redirect_to root_path
  end

  def delete
    course_id = params[:id].to_i
    session[:cart].delete(course_id)
    redirect_to root_path
  end

  def show
    require 'json'
    require 'stripe'

    @currentUser = current_user



    #Customer info
    @customerInfo = CustomerInfo.find_by(user_id: @currentUser.id)

    @items_in_cart = session[:cart]
    @test ||= [];
    @subtotal_price = 0;
    @items_in_cart.each do |n|
      @test << Course.find(n)
      @subtotal_price += Course.find(n).price
    end
    if !CustomerInfo.find_by(user_id: @currentUser.id).nil?
      @gst_in_dollars = (@subtotal_price * Province.find_by(id:@customerInfo.province_id).GST)
      @pst_in_dollars = (@subtotal_price * Province.find_by(id:@customerInfo.province_id).PST)
      @hst_in_dollars = (@subtotal_price * Province.find_by(id:@customerInfo.province_id).HST)
      @total_price = @subtotal_price + @hst_in_dollars

    end


  end

  def addRegion
    info = CustomerInfo.create(
        address:       params[:address],
        user_id:       params[:id],
        province_id:   params[:province_id]
      )
      #Updates information on stripe
  Stripe::Customer.update(
    User.find(current_user.id).stripe_customer_id.to_s,
    {
      phone: "1#{params[:phone].to_s}",
      name: params[:fullName].to_s,
      address: {
        country: 'CA',
        line1: params[:address].to_s,
        state: Province.find(params[:province_id]).Province_Name.to_s,
      },
      shipping: {
        address: {
          country: 'CA',
          line1:  params[:address].to_s,
          state: Province.find(params[:province_id]).Province_Name.to_s,
        },
        name: params[:fullName].to_s,
        phone: "1#{params[:phone].to_s}",
      },
    },
  )
      flash[:success]= "Successfully updated user information!"
      if(!session[:cart].nil?)
        redirect_to cart_path
      else
        redirect_to root_path
      end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # root_path
  def index
    @courses = Course.includes(:category).order('RANDOM()').page(params[:page]).per(300).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<div class="card text-center">
  <div class="card-body bg-primary-subtle">
    <h5 class="card-title">Thank U for visiting!</h5>
    <p class="card-text">Check our github repo below to see how we made this <em>Ruby on Rails</em>
      application from the ground up.</p>
    <a href="https://github.com/xammyboii/uLearn">uLearn repository</a>
  </div>
  <div class="card-footer text-body-secondary">
    &copy; <%= Time.current.year %> uLearn. All Rights Reserved.
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary-subtle">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'uLearn', root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto nav-fill navbar-nav-scroll">
        <%# Logged In User Conditional %>
        <% if user_signed_in? %>
          <li class="nav-item">
            <p class="navbar-text" style="margin-bottom: 0px; margin-right: 10px">Hi, <%= link_to current_user.email, "/user/#{current_user.id}" %></p>
          </li>
          <li class="nav-item">
            <%#= button_to "Sign out", destroy_user_session_path, class: 'btn btn-outline-primary', method: :delete %>
            <%= button_to destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary' do %>
              Sign Out <i class="fas fa-right-from-bracket"></i>
            <% end %>
          </li>
          <% if !session[:cart].nil?%>
            <li class="nav-item">
              <%= button_to "/cart", method: :get, class: 'btn btn-primary' do %>
                Checkout <i class="fa-solid fa-cart-shopping"></i>
              <% end %>
            </li>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'btn btn-outline-primary' do %>
              Sign In <i class="fas fa-right-to-bracket"></i>
            <% end %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "About", courses_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class:"nav-link" %>
        </li>
      </ul>
      <%= render 'categories/categories_dropdown' %>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>uLearn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/9cb03bfea0.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://js.stripe.com/v3"></script>
    <script>
      Stripe.setPublishableKey("pk_test_51OJgI5B7ve0qtzXwEFXgQOBpDcs4IHqGW7nYYHYCL2I2pi6iMLSvEtQV5sjwkYyg3KQS67hXY3iB96vxexjZQuk400C9p9uy5X");
    </script>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main class="container">
      <p class="notice">
        <%= notice %></p>
      <p class="alert">
        <%= alert %></p>
      <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>